package ua.kharkov.koni.konikharkov.greenDAO;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import ua.kharkov.koni.konikharkov.entity.Amortizator;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig amortizatorDaoConfig;

    private final AmortizatorDao amortizatorDao;

    DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        amortizatorDaoConfig = daoConfigMap.get(AmortizatorDao.class).clone();
        amortizatorDaoConfig.initIdentityScope(type);

        amortizatorDao = new AmortizatorDao(amortizatorDaoConfig, this);

        registerDao(Amortizator.class, amortizatorDao);
    }
    
    public void clear() {
        amortizatorDaoConfig.clearIdentityScope();
    }

    public AmortizatorDao getAmortizatorDao() {
        return amortizatorDao;
    }

}
